### PR TITLE
added incl_timepoints parameter

### PR DESCRIPTION
**Pull request by smerdis**
allows caller to specify a subset of timepoints, so that we can look at only one condition, etc.

### CODE REVIEW

**Comment by mb3152** [comment]
new_subject_time_series_data = np.delete(new_subject_time_series_data,np.where(i_tps==False),axis=3)

shouldn't "i_tps==False" be equal to "i_tps==0", for sake of clarity?

**Comment by smerdis** [comment]
yeah, it would be more consistent and not rely on that equivalence. i'll submit a fix in a second.

**Comment by smerdis** [comment]
Okay, bunch of new changes. There is now a parse_evs.py that has functions to handle getting of timepoints with built-in sanity checks. There's also some code at the bottom setting up two of the tasks.

**Comment by mb3152** [comment]
looks good, but we should keep the parse evs stuff separate from this repo.

**Comment by smerdis** [comment]
Okay, removed. Should I just make a new personal repo for the parse_evs stuff?

**Comment by mb3152** [comment]
yes, you can share it with me and then we can work on it together.

**Pull request merged**
